project:
  type: website
  output-dir: docs

website:
  title: "Max Bonetati"
  navbar:
    right:
      - about.qmds
      - Project.qmd
      - Adventures.qmd
      - Resume.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full

editor: visual

