project:
  type: website
  output-dir: docs

website:
  title: "Max Bonetati"
  navbar:
    right:
      - text: "About Me"
        href: AllAboutMe.qmd
      - text: "Adventures"
        href: Adventures.qmd
      - text: "Project"
        href: Project.qmd
      - text: "Resume"
        href: Resume.qmd
      
      

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true
    page-layout: full

editor: visual

